### ISSUE TITLE
All possible api responses?

### ISSUE THREAD

**Issue by hhsnopek** [itsabot/plugin_weather#1]
Hey I'm currently writing a plugin that consumes your api, I'm curious if you'd be able to provide all the possible values for the description array. 😄 Thank you!

``` json
{"Description":["clear sky"],"Temp":35.13,"Humidity":69}
```

**Comment by egtann** [comment]
I just receive it from Open Weather Map using a free API key. The itsabot.org endpoint is really more for demo purposes. If you'd like to customize results or to use it in production I'd recommend signing up here: http://openweathermap.org/api

You can see how we handle parsing the responses in https://github.com/itsabot/itsabot.org inside `server.go`. Look for the Weather endpoint.

**Comment by hhsnopek** [comment]
👍 thanks - I'll switch endpoints then 😄
